main() {
  APK=NativeExample.apk

  if [ -z "$ANDROID_SDK" ]; then
    if [ -n "$ANDROID_HOME" ]; then
      ANDROID_SDK="$ANDROID_HOME"
    elif [ -n "$ANDROID_SDK_ROOT" ]; then
      ANDROID_SDK="$ANDROID_SDK_ROOT"   
    else
      ANDROID_SDK="$HOME/android/sdk"
      echo "Defaulting ANDROID_SDK to $ANDROID_SDK"
    fi
  fi

  if [ -z "$ANDROID_NDK" ]; then
    ANDROID_NDK="$ANDROID_SDK/ndk"
    echo "Defaulting ANDROID_NDK to $ANDROID_NDK"
  fi

  if [ -z "$JAVA_JDK" ]; then
    if [ -n "$JAVA_HOME" ]; then
      JAVA_JDK="$JAVA_HOME"
    else
      echo "Missing Java env. (aka JAVA_HOME or JAVA_JDK)"
      exit 1
    fi
  fi

  if [ ! -d "$ANDROID_NDK" ] || [ ! -d "$ANDROID_SDK" ] || [ ! -d "$JAVA_JDK" ]; then
    echo "Yor SDK env isn't correctly setup."
    echo "All these env. variables should be exported:"
    echo "  ANDROID_NDK"
    echo "  ANDROID_SDK / ANDROID_HOME / ANDROID_SDK_ROOT"
    echo "  JAVA_JDK / JAVA_HOME"
    exit 1
  fi

  check || exit 1

  gen_clangd

  if [ "$1" == "run" ];     then run; exit $?; fi
  if [ "$1" == "build" ];   then build; exit $?; fi
  if [ "$1" == "remove" ];  then remove; exit $?; fi
  if [ "$1" == "install" ]; then install; exit $?; fi
  if [ "$1" == "launch" ];  then launch; exit $?; fi
  if [ "$1" == "log" ];     then log; exit $?; fi
  if [ "$1" == "" ];        then go; exit $?; fi

  echo "Usage: $0 [command]"
  echo "By default build, install and run .apk file."
  echo 
  echo "Optional [command] can be:"
  echo "  run       - only install and run .apk file"
  echo "  build     - only build .apk file"
  echo "  remove    - remove installed .apk"
  echo "  install   - only install .apk file on connected device"
  echo "  launch    - ony run already installed .apk file"
  echo "  log       - show logcat"
}

gen_clangd() {
  echo "# Autogenerated file for Clangd LSP
CompileFlags:
  Add:
    - -I$ANDROID_NDK/sysroot/usr/include/
    - -I$ANDROID_NDK/sysroot/usr/include/EGL/
    - -I$ANDROID_NDK/sources/android/native_app_glue/" > .clangd
}


go() {
  build   || exit 1
  install || exit 1
  launch  || exit 1
}

run() {
  install || exit 1
  launch  || exit 1
}

build() {
  mkdir -p "bin"
  rm -f "$out"

  $ANDROID_NDK/ndk-build NDK_LIBS_OUT=lib/lib
  if [ $? -ne 0 ]; then
    echo "build: ndk-build failed"
    exit 1
  fi

  # $ANDROID_SDK/build-tools/$BUILD_TOOLS/aapt package -f -M AndroidManifest.xml -I "$ANDROID_SDK/platforms/$PLATFORM/android.jar" -A assets -F "bin/$APK.build" lib
  aapt2="$ANDROID_SDK/build-tools/$BUILD_TOOLS/aapt2"
  out="bin/$APK.build"
 
  $aapt2 compile --dir "res" -o "bin"
  if [ $? -ne 0 ]; then
    echo "build: aapt compile failed"
    exit 1
  fi

  $aapt2 link \
    -o "$out" \
    -I "$ANDROID_SDK/platforms/$PLATFORM/android.jar" \
    --manifest "AndroidManifest.xml" \
    -A "assets"\
    bin/*.flat

  if [ $? -ne 0 ]; then
    echo "build: aapt link failed"
    exit 1
  fi

  ( 
    cd lib 
    zip -r "../$out" lib/ 
  )

  if [ ! -f ".keystore" ]; then
    $JAVA_JDK/bin/keytool -genkey -dname "CN=Android Debug, O=Android, C=US" -keystore .keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -validity 30000
    if [ $? -ne 0 ]; then
      echo "build: Can't generate debug keystore"
      exit 1
    fi
  fi

  $ANDROID_SDK/build-tools/$BUILD_TOOLS/zipalign -f 4 "$out" "bin/$APK"
  if [ $? -ne 0 ]; then
    echo "build: Can't zipalign APK"
    exit 1
  fi

  $ANDROID_SDK/build-tools/$BUILD_TOOLS/apksigner sign --ks .keystore --ks-key-alias androiddebugkey --ks-pass pass:android "bin/$APK"
  if [ $? -ne 0 ]; then
    echo "build: Error while signing APK"
    exit 1
  fi
}

remove() {
  get_package_activity
  $ANDROID_SDK/platform-tools/adb uninstall $PACKAGE
  if [ $? -ne 0 ]; then
    exit 1
  fi
}

install() {
  $ANDROID_SDK/platform-tools/adb install -r "bin/$APK"
  if [ $? -ne 0 ]; then
    exit 1
  fi
}

launch() {
  get_package_activity
  $ANDROID_SDK/platform-tools/adb shell am start -n "$PACKAGE/$ACTIVITY"
  if [ $? -ne 0 ]; then
    exit 1
  fi
}

log() {
  $ANDROID_SDK/platform-tools/adb logcat -d NativeExample:V *:S
  if [ $? -ne 0 ]; then
    exit 1
  fi
}

get_package_activity() {
  ACTIVITY=""
  PACKAGE=""

  # This is probably the worst way to implement this, but I don't know a better solution.... 
  pkg=$(
    $ANDROID_SDK/build-tools/$BUILD_TOOLS/aapt dump badging "bin/$APK" |
      while IFS= read -r line; do
        if [[ "$line" == "package:"* ]]; then
          echo "PACKAGE=$(sed "s/.* name='\([^']*\)'.*/\1/"  <<< "$line")"
        fi

        if [[ "$line" == "launchable-activity:"* ]]; then
          echo "ACTIVITY=$(sed "s/.* name='\([^']*\)'.*/\1/"  <<< "$line")"
        fi
      done
  )

  eval $pkg
}

check() {
  if [ ! -f "$ANDROID_NDK/ndk-build" ]; then
    echo "Android NDK not found in $ANDROID_NDK"
    return 1
  fi

  if [ ! -d "$ANDROID_SDK" ]; then
    echo "Android SDK not found in $ANDROID_SDK"
    return 1
  fi
  
  if [ ! -f "$JAVA_JDK/bin/javac" ]; then
    echo "Java JDK not found in $JAVA_JDK"
    return 1
  fi
  
  if [ ! -f "$ANDROID_SDK/platform-tools/adb" ]; then
    echo "Please install Android SDK Platform-tools"
    return 1
  fi
  
  BUILD_TOOLS=$(ls "$ANDROID_HOME/build-tools/" | sort -r | head -n 1)
  tools_ok
}

tools_ok() {
  if [ ! -f "$ANDROID_SDK/build-tools/$BUILD_TOOLS/aapt" ]; then
    echo "Please install Android SDK Build-tools"
    return 1
  fi

  PLATFORM=$(ls "$ANDROID_SDK/platforms" | sort -r | head -n 1)
  platform_ok
}

platform_ok() {
  if [ ! -f "$ANDROID_SDK/platforms/$PLATFORM/android.jar" ]; then
    echo "Please install at least one Android SDK platform"
    return 1
  fi
}

main $@
